# Generated by Django 5.1 on 2025-03-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
